name: NPM Test

on:
  pull_request:
    branches:
      - develop
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm run flb

      - name: Check test result
        run: |
          if [ $? -eq 0 ]; then
            echo "Tests passed"
          else
            echo "Tests failed"
            exit 1
          fi
